language: node_js
node_js:
    - "0.12"
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install